### ISSUE TITLE
Origin/RP ID verification does not allow for subdomains

### ISSUE THREAD

**Issue by PhilippParis** [Yubico/java-webauthn-server#14]
Steps to reproduce:
1. use "example.com" as RP ID
2. register/authenticate credential on origin "https://login.example.com"

As stated in [W3C-Webauthn](https://w3c.github.io/webauthn/#rp-id) the public key credentials can be used within subdomains of the RP ID:

> For example, given a Relying Party whose origin is https://login.example.com:1337, then the following  RP IDs are valid: login.example.com (default) and example.com, but not m.login.example.com and not  com.

**Comment by emlun** [comment]
You need to set the [`origins`](https://yubico.github.io/java-webauthn-server/webauthn-server-core/com/yubico/webauthn/RelyingParty.RelyingPartyBuilder.html#origins-java.util.Set-) parameter of the `RelyingParty` class.

Thanks for the report! I should probably point this out in the docs, but I'm not sure where. Where did you look for information on this before opening the issue?

**Comment by PhilippParis** [comment]
Hi!
Thanks for your response!
I have looked into to RelyingParty and the FinishRegistrationSteps/FinishAssertionSteps classes and I have seen the origins parameter. Altough due to multiple RelyingParties and origins it would be easier if the subdomain check would be implicit. 
But I will look into developing a solution by using the origins parameter!

Another question while I am here:
Do you have any idea if the yubico fido2 keys will be added to the MetadataService of the fido-alliance?
Or will you stick to your custom metadata json?

Thanks!

**Comment by emlun** [comment]
Yeah, I went with an explicit whitelist solution for starters for two main reasons: it's easier (i.e., smaller risk of security bugs), and wildcards in general for security parameters should be used with caution. Maybe we'll add an option to explicitly opt into some kind of wildcard subdomain matching if demand for it is high enough.

I'm pretty sure our FIDO2 keys are in the FIDO MDS already. We haven't implemented direct integration with the MDS into this library yet, but it's something we would like to do eventually. If/when we do, it should hopefully require only minimal changes to application code to make use of it.

**Comment by emlun** [comment]
I opened #15 to track demand for wildcard matching. I think most questions here have been answered, so I'll close this; you're welcome to re-open it if there's anything else you'd like to discuss.
