### ISSUE TITLE
Incorret origin for Android 

### ISSUE THREAD

**Issue by rochards** [Yubico/java-webauthn-server#159]
Hello, 

I'm trying to store a credential using Android SafetyNet Attestion, but a get an Exception: `Incorret origin: android:apk-key-hash:<some-rash-here>`. Is it some misconfiguration from my server?

Thank you.

**Comment by emlun** [comment]
Hi! Yes, you'll need to add the origin for your app using the [`.origins(Set<String>)` setting](https://developers.yubico.com/java-webauthn-server/JavaDoc/webauthn-server-core-minimal/latest/com/yubico/webauthn/RelyingParty.RelyingPartyBuilder.html#origins(java.util.Set)) of the `RelyingParty` class. Note that this will overwrite the default (`"https://<RP ID>"`), so if you also need to support a web origin you'll need to include that too.
