### ISSUE TITLE
CBOR dependency range is not working

### ISSUE THREAD

**Issue by renatoathaydes** [Yubico/java-webauthn-server#168]
Hi, I've noticed a problem regarding this project's dependency resolution in Gradle.

You have declared dependency ranges for most libraries, which is nice. However , because transitive dependencies may have fixed versions, Gradle will give those fixed versions priority.

We found this problem when we noticed that the CBOR library used by this project was resolving to an old version which has known vulnerabilities.

To confirm that behaviour, you can try this small Gradle file:

```groovy
configurations {
    api
}

repositories {
    mavenCentral()
}

dependencies {
    api 'com.yubico:webauthn-server-core:1.12.1'
}

task downloadDeps(type: Copy) {
    from configurations.api
    into file('libs') 
}
```

In this project's build file, notice how you define this dependency on CBOR:

```groovy
api('com.upokecenter:cbor:[4.0.1,5)')
```

But when running `gradle downloadDeps` with the above file, I get these libraries:

```
bcprov-jdk15on-1.70.jar
cbor-4.0.1.jar
checker-qual-3.8.0.jar
commons-codec-1.11.jar
commons-logging-1.2.jar
cose-java-1.1.0.jar
eddsa-0.3.0.jar
error_prone_annotations-2.5.1.jar
failureaccess-1.0.1.jar
guava-30.1.1-jre.jar
httpclient-4.5.13.jar
httpcore-4.4.13.jar
j2objc-annotations-1.3.jar
jackson-annotations-2.13.1.jar
jackson-core-2.13.1.jar
jackson-databind-2.13.1.jar
jackson-dataformat-cbor-2.13.1.jar
jackson-datatype-jdk8-2.13.1.jar
jsr305-3.0.2.jar
listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
numbers-1.4.3.jar
slf4j-api-1.8.0-beta4.jar
webauthn-server-core-1.12.1.jar
webauthn-server-core-minimal-1.12.1.jar
yubico-util-1.12.1.jar
```

The relevant jar is `cbor-4.0.1.jar`. This is an old version as you can [see here](https://search.maven.org/artifact/com.upokecenter/cbor)... the latest version (which doesn't have vulnerabilities) is **4.5.2**.

I believe the reason this is happening is that CBOR is a transitive dependency of your other dependency, `api('com.augustcellars.cose:cose-java:[1.0.0,2)')`. You're already depending on the latest [cose-java](https://search.maven.org/artifact/com.augustcellars.cose/cose-java) version, so you can't update it.

When I change my Gradle file above to exclude `cose-java` like this:

```groovy
dependencies {
    api 'com.yubico:webauthn-server-core:1.12.1', {
        exclude module: 'cose-java'
    }
}
```

Then, I get the latest CBOR version as expected.

I wanted to bring this up with you because unfortunately, the dependency ranges simply don't work as it is.

I know it's easy to "fix" this on the consumer side by using Gradle standard dependency resolution overrides (which is what I've done) but it feels very fragile that the ranges are not working by default.

One way to fix it for now might be to exclude `cose-java`'s transitive dependencies from your dependencies like this:

```groovy
api('com.augustcellars.cose:cose-java:[1.0.0,2)') {
  transitive = false
}
```

This allows Gradle to resolve the version range for CBOR correctly, but risks you missing transitive dependencies from `cose-java` in the future if they change/add dependencies.

 I am not sure there's anything else that can be done other than ask the `cose-java` maintainers to also use version ranges and update their own dependencies to the latest versions.

**Comment by emlun** [comment]
Hi! Thanks for letting us know about this. You can actually fix it downstream by adding a [dependency constraint](https://docs.gradle.org/current/userguide/dependency_constraints.html#sec:adding-constraints-transitive-deps):

```
dependencies {
  constraints {
    implementation('com.upokecenter:cbor:[4.5.2,5)')
  }
}
```

I will bump that version constraint in the library too.

Where did you find information about the known vulnerabilities in `com.upokecenter:cbor:4.0.1`?

**Comment by renatoathaydes** [comment]
No problem. We already fixed the problem on our side, but we thought many consumers of this library might not even realize this is happening.

The vulnerability: https://github.com/advisories/GHSA-fj2w-wfgv-mwq6

**Comment by emlun** [comment]
Hm, actually, any `com.upokecenter:cbor` version later than `4.0.1` makes the tests fail with a `Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot find a (Map) Key deserializer for type [simple type, class com.upokecenter.cbor.CBORObject]` when trying to deserialize an `AuthenticatorData` value. I'll have to dig a bit more into this before I make a release with the version bump...

**Comment by renatoathaydes** [comment]
Not that this matters for this particular issue anymore, but I ran some tests and found that only Gradle was incorrectly pulling the old dependency version... Maven correctly resolved the newer version in my tests.

This means that, likely, most users were not getting that old library as Maven seems to still be the most popular tool, luckily in this case.

I will report the issue to Gradle and see what they say.
