### ISSUE TITLE
module core-minimal and attestion conflicting in JPMS

### ISSUE THREAD

**Issue by goodidea-kp** [Yubico/java-webauthn-server#170]
not compilable due to '.resolver' package belongs to a different package - JPMS violation. version 1.12.2

**Comment by emlun** [comment]
Sorry, I don't understand what you mean. Could you elaborate a bit? And sorry for not responding for so long, somehow I missed this.

**Comment by goodidea-kp** [comment]
I want to implement Yubikey libs into my Java App based on JPMS (Java Package Module System). One of the very important requirements from JPMS is: 1 jar must have a unique package name for a given class. in your code "core-minimal" jar and "attestation" has the same package name (overlapping by name "com.yubico.webauthn.attestation") that is a direct violation of JPMS requirements. That is blocking the seamless integration of Yubikey librarires.

**Comment by emlun** [comment]
Ah, I see. That will take a major version release to fix, so we should make sure to get that done in the upcoming 2.0.

In the meantime, if it's any consolation, you don't really need the attestation module to get started with WebAuthn. All it really adds is an implementation of the `MetadataService` instance that works with a Yubico-specific JSON format for attestation metadata. This is also set to change in 2.0, which will replace all of that with an integration with the FIDO Metadata Service instead.

**Comment by goodidea-kp** [comment]
I sorted it out.. thanks!

**Comment by emlun** [comment]
This should now be fixed in the 2.0.0 release. Thanks again!
