### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by drozzy** [Yubico/java-webauthn-server#2]
Any chance for a more permissive license? Like MIT?

**Comment by drozzy** [comment]
Can I use put BSD code into a closed-source system?

**Comment by emlun** [comment]
Yes, provided you honor the conditions in the license. I'll look over the packaging to see that all JARs include the COPYING file to make it difficult to accidentally not honor the license.

**Comment by emlun** [comment]
Fixed in 09a9d83369a066c91f7ba3f3b471a116bd5d2804.
