### ISSUE TITLE
How to limit the number of available factors

### ISSUE THREAD

**Issue by igorlogvin** [Yubico/java-webauthn-server#200]
Hello again @emlun ! I tried read [this](https://www.w3.org/TR/webauthn-2/#sctn-uvm-extension) section.

I need to limit the number of factors to identify a user through webauth. I need to exclude pin code input from authentication. That is, for example, on an iPhone, if a face reads it incorrectly several times, then it is proposed to enter a pin code. So I need to somehow exclude this operation and leave only face or touch ID.

Can u please explain me how?

**Comment by igorlogvin** [comment]
Okay, Emil. Thanks for the answer.

It seems that we have no choice but to warn the user that if an attacker gains access to the phone, he will be able to use webauthn using the selection of a pin code, since iOs, after several unsuccessful attempts to read the face, suggests entering a pin code. Here, most likely, the options will not pass by the timeout that is set in the start options.

**Comment by emlun** [comment]
Yes, most authenticators allow fallback to a PIN or similar since biometrics can be unreliable even for the legitimate user. Also note that clients MAY override the [`timeout`](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#dom-publickeycredentialrequestoptions-timeout) option if they like.
