### ISSUE TITLE
Support "hybrid" transport type

### ISSUE THREAD

**Issue by jessejacksonafterpay** [Yubico/java-webauthn-server#230]
The transport type "hybrid" is now officially part of the spec, so would be great if this was supported in the enum type.

https://github.com/w3c/webauthn/commit/656e61356345c709292b6b2fcaaff7a57a82bf33

**Comment by emlun** [comment]
Yes, thanks for the poke! This will be included in release `2.1.0`.

**Comment by emlun** [comment]
Sorry, forgot to update the issue. Release `2.1.0` is out since October, including this feature.
