### ISSUE TITLE
Invalid TPM attestation certificate

### ISSUE THREAD

**Issue by ozzi-** [Yubico/java-webauthn-server#240]
Hi there

I just checked out aca3c5d07df01d3306102c8e08de603936311cb8 and ran the demo.
On my Thinkpad X1 Gen9 as well as a Thinkpad T14 Gen 3 (both have a reasonably new TPM), I receive the following error when trying to register:
`java.lang.IllegalArgumentException: Invalid TPM attestation certificate: The Subject Alternative Name extension MUST be set as defined in [TPMv2-EK-Profile] section 3.2.9. Missing TPM model. Missing TPM version.`

Might this be a bug or do I have two devices with unsuitable hardware? Any hints would be great.

Cheers

**Comment by ozzi-** [comment]
TPMVersion, TPMModel and TPMManufacturer should be present. I don't know how to check the SAN of the attestation cert though..
![image](https://user-images.githubusercontent.com/7944573/199462632-cd6fc6c0-3fb3-4764-90d5-4e2c109877d3.png)

**Comment by ozzi-** [comment]
I did some digging and created a PR which fixes this issue:
https://github.com/Yubico/java-webauthn-server/pull/241

**Comment by emlun** [comment]
The fix from PR #241 is available now in [pre-release 2.2.0-RC1](https://github.com/Yubico/java-webauthn-server/releases/tag/2.2.0-RC1). As usual we'll wait about 2 weeks before promoting it to a finished `2.2.0` release. Thanks again!
