### ISSUE TITLE
The method toCredentialsCreateJson() is undefined

### ISSUE THREAD

**Issue by MrMaavin** [Yubico/java-webauthn-server#244]
I don't know if I missed something but i tired the following code and got the error "_The method toCredentialsCreateJson() is undefined for the type PublicKeyCredentialCreationOptions_".

```
PublicKeyCredentialCreationOptions pkcco =
        rp.startRegistration(StartRegistrationOptions.builder().user(findExistingUser("alice").orElseGet(() -> {
          byte[] userHandle = new byte[64];
          random.nextBytes(userHandle);
          return UserIdentity.builder().name("alice").displayName("Alice Hypothetical").id(new ByteArray(userHandle))
              .build();
        })).build());

PublicKeyCredentialCreationOptionsBuilder credentialCreateJson = pkcco.toCredentialsCreateJson();
```
I use the following dependency:

```
<dependency>
        <groupId>com.yubico</groupId>
	<artifactId>webauthn-server-core</artifactId>
	<version>1.9.1</version>
</dependency>
```

What is wrong? Should i provide more Info and if yes what kind of info?

**Comment by emlun** [comment]
Hi! That feature was introduced in [version `1.11.0`](https://github.com/Yubico/java-webauthn-server/releases/tag/1.11.0), so you'll need to upgrade to at least that to use that method. Otherwise you'll need to [use a Jackson `ObjectMapper`](https://github.com/Yubico/java-webauthn-server/tree/1.10.0#registration) or other serialization tool to convert it to JSON.

**Comment by MrMaavin** [comment]
> Hi! That feature was introduced in [version `1.11.0`](https://github.com/Yubico/java-webauthn-server/releases/tag/1.11.0), so you'll need to upgrade to at least that to use that method. Otherwise you'll need to [use a Jackson `ObjectMapper`](https://github.com/Yubico/java-webauthn-server/tree/1.10.0#registration) or other serialization tool to convert it to JSON.

Thanks a lot, that helped me. Maybe that can be updated on the [Yubico Java webpage](https://developers.yubico.com/java-webauthn-server/).
