### ISSUE TITLE
How can I build webauthn in an offline?

### ISSUE THREAD

**Issue by DoyeongJoo** [Yubico/java-webauthn-server#25]
Is there a way to configure and run the java-webauthn-server environment where no Internet connection is available?

I would like to know more about how to build a build environment without using gradle or maven.

**Comment by emlun** [comment]
Certainly, the library makes no connections to the internet and should work completely fine without an internet connection.

If you're not using Gradle, Maven or Ivy for your project, you can download the `.jar` artifact(s) from [Maven Central][central] and import it into your project like any other `.jar` file.

[central]: https://mvnrepository.com/artifact/com.yubico/webauthn-server-core/1.3.0
