### ISSUE TITLE
RegistrationResult Builder is not public

### ISSUE THREAD

**Issue by ed5s** [Yubico/java-webauthn-server#26]
Hi @emlun, It would be very helpful If you could set the visibility of `RegistrationResultBuilder` as `public`. Thank you very much In advance.

**Comment by emlun** [comment]
Why do you need to construct that class?

**Comment by ed5s** [comment]
Just to be able to deserialize this class using a distributed cache instead of Guava cache.

**Comment by emlun** [comment]
Why do you need to cache it?

**Comment by emlun** [comment]
I'm sorry, I'm not trying to be difficult, I'm just trying to understand your use case in case that has wider implications for the overall design of the library.
