### ISSUE TITLE
Update metadata for black FIDO keys for demo server

### ISSUE THREAD

**Issue by joostd** [Yubico/java-webauthn-server#261]
Please update `webauthn-server-demo/src/main/resources/metadata.json`
to include metadata for:
- Security Key NFC Black ( USB-A , USB-C ), AAGUID a4e9fc6d-4cbe-4758-b8ba-37598bb5bbaa
and
- Security Key NFC - Enterprise Edition ( USB-A , USB-C ), AAGUID 0bb43545-fd2c-4185-87dd-feb0b2916ace

**Comment by emlun** [comment]
Thanks! Fixed in 63d6af10a130909eef1f14b0ef02cd9950bd829b.
