### ISSUE TITLE
Serialize RegistrationRequest and AssertionRequestWrapper

### ISSUE THREAD

**Issue by devmanspi** [Yubico/java-webauthn-server#27]
Is there a way to serialize RegistrationRequest and AssertionRequestWrapper Objects? I want to store them in a DB to use the DB as shared cache.

**Comment by emlun** [comment]
Those two classes are from the demo application and not the library. You're free to implement the request packaging however you like in your application.

**Comment by devmanspi** [comment]
Thanks for the fast reply.
But both classes have publicKeyCredentialRequestOptions which is not serializable and from the library.

**Comment by emlun** [comment]
Ok, that sounds like a duplicate of #18.
