### ISSUE TITLE
Automatic-Module-Name

### ISSUE THREAD

**Issue by jbb01** [Yubico/java-webauthn-server#276]
For better compatibility with the JPMS (Java Platform Module System) it would be desirable to either have an `Automatic-Module-Name` defined in the `META-INF` file or a `module-info.java` (possibly as a multi-release JAR).

Otherwise (maven) builds using the JPMS that depend on this library will produce a warning:

```
[WARNING] ******************************************************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [webauthn-server-core-2.4.1.jar]. Please don't publish this project to a public artifact repository! *
[WARNING] ******************************************************************************************************************************************************************************
```

**Comment by emlun** [comment]
Fixed in PR #303 and available in [pre-release `2.5.0-RC1`](https://github.com/Yubico/java-webauthn-server/releases/tag/2.5.0-RC1).
