### ISSUE TITLE
Does this support JDK 7, 6 and below?

### ISSUE THREAD

**Issue by DoyeongJoo** [Yubico/java-webauthn-server#28]
Seems like couple of people mentioned about compiling on JDK 8 and above environment, but I am considering using this library on below JDK 7 (probably 6). 

I know it's not optimal to use it on such legacy settings and I understand it can be exhausting to check compatibilities, but it would be awesome to know if it will work or not.

Thanks.

**Comment by emlun** [comment]
Sorry, no, the minimum supported JDK version is JDK 8.
