### ISSUE TITLE
Unknown credential

### ISSUE THREAD

**Issue by DeenOub** [Yubico/java-webauthn-server#29]
Hi,

I am trying to implement a FIDO2 server and I have an issue in finishAuthentication : I am using the finishAssertion method to validate the request : 
```
AssertionResult result = rp.finishAssertion(FinishAssertionOptions.builder().request(request).response(response).build());
```

but I am experimenting this error : 
```
java.lang.IllegalArgumentException : Unknown credential: ByteArray(...)
```
This error seems to come from [FinishAssertionSteps line 202](https://github.com/Yubico/java-webauthn-server/blob/master/webauthn-server-core/src/main/java/com/yubico/webauthn/FinishAssertionSteps.java) and this is maybe because my `userHandle` is empty. However I thought `userHandle` could be empty. How can I resolve this issue ?

Thank you for your help.
DeenOub

**Comment by emlun** [comment]
Hi!

It looks like the call to `credentialRepository.lookup(response.getId(), userHandle)` returns an `Optional.empty()`, so this would depend on how you've implemented `CredentialRepository`. It seems like your [`lookup`][lookup] implementation is returning `Optional.empty()` for the given credential ID and user handle.

The zero-length byte array is a valid value for `userHandle`, but this library probably won't behave well if more than one user has the same user handle.

[lookup]: https://github.com/Yubico/java-webauthn-server/blob/master/webauthn-server-core/src/main/java/com/yubico/webauthn/CredentialRepository.java#L68

**Comment by emlun** [comment]
Oh, and I was about to say: also note that some versions of Chrome return an empty `userHandle` instead of `null`, see issue #12. It looks like that was [fixed recently](https://bugs.chromium.org/p/chromium/issues/detail?id=847878), but I don't know how far it's been rolled out yet.

**Comment by DeenOub** [comment]
Issue solved ! It was indeed in my implementation of `CredentialRepository`, I didn't make the right conversion String to ByteArray. Now it's ok and my authentication works perfectly. Thanks a lot emlun !

**Comment by emlun** [comment]
Good to hear! And a friendly reminder: also make sure to test that authentication fails given wrong/invalid credentials, that's arguably more important than the happy path. :slightly_smiling_face:
