### ISSUE TITLE
Invalid attestation signature.

### ISSUE THREAD

**Issue by hamfernandes** [Yubico/java-webauthn-server#31]
Hello.

I'm trying to register a security key NFC from yubico in a demo application I'm implementing, but I'm having some trouble while trying to register it.
In my client side I construct the object to send to the server for registration like this (publicKeyCredential is the object I get from executing navigator.credentials.create):

```
const decodedClientDataJSON=utf8Decoder.decode(publicKeyCredential.response.clientDataJSON);
const parsedClientDataJSON=JSON.parse(decodedClientDataJSON);
parsedClientDataJSON.challenge=atob(parsedClientDataJSON.challenge);

var newClientDataJSON=utf8Encoder.encode(JSON.stringify(parsedClientDataJSON));

var newResponse={
            attestationObject: this.mimeBase64ToUrl(base64js.fromByteArray(this.ensureUint8Array(publicKeyCredential.response.attestationObject))),
            clientDataJSON: this.mimeBase64ToUrl(base64js.fromByteArray(this.ensureUint8Array(newClientDataJSON)))
        };

let bodyJSON=JSON.stringify({
            requestId: this.state.requestId,
            credential: {
                type: publicKeyCredential.type,
                id: publicKeyCredential.id,
                response: newResponse,
                clientExtensionResults: publicKeyCredential.getClientExtensionResults()
            }
        });
```

The function mimeBase64ToUrl is the one present in the demo of this repo.
I send this to the server for registration but I'm getting  
`Invalid attestation signature.`

I see in https://github.com/Yubico/java-webauthn-server/blob/master/webauthn-server-core/src/main/java/com/yubico/webauthn/FinishRegistrationSteps.java that the `verifier.verifyAttestationSignature(attestation, clientDataJsonHash)` fails, but is this caused by the way I encode clientDataJSON here on the client side?

I also saw #6 but I'm enconding clientDataJSON in Base64.

Thanks in advance.

**Comment by emlun** [comment]
Hi!

At first glance it looks like this has to do with your re-coding the `clientDataJSON`. The `response.clientDataJSON` is returned as a byte array rather than a proper JSON data structure or string because for verifying the signature you need the exact sequence of bytes that was signed. There's no guarantee that a round-trip through `JSON.parse` and `JSON.stringify` will give you back the exact same byte sequence even if it's semantically equal JSON.

Try changing

```
var newResponse={
            attestationObject: ...,
            clientDataJSON: this.mimeBase64ToUrl(base64js.fromByteArray(this.ensureUint8Array(newClientDataJSON)))
        };
```

to

```
var newResponse={
            attestationObject: ...,
            clientDataJSON: this.mimeBase64ToUrl(publicKeyCredential.response.clientDataJSON)
        };
```

and see if that helps.

**Comment by hamfernandes** [comment]
Thank you very much for the prompt reply @emlun.
Ok, that's right. At a first implementation I was making that but in the server I was getting 
`Incorrect challenge.`

So I made this rewriting of the clientDataJSON, decoding the challenge and reconstructing the clientDataJSON, because I thought that I had to decode the challenge before sending it to the server.

**Comment by emlun** [comment]
Ok. You shouldn't need to decode the challenge before sending the response back to the server, but you do need to [base64 decode the challenge][decode] before [sending it into `navigator.credentials.create()`][create].

You can verify if it's going well by inspecting the argument you're passing to [`RelyingParty.finishRegistration`][fr]. The fields `finishRegistrationOptions.getRequest().getChallenge()` and `finishRegistrationOptions.getResponse().getResponse().getClientData().getChallenge()` should be exactly equal.

[create]: https://github.com/Yubico/java-webauthn-server/blob/master/webauthn-server-demo/src/main/webapp/js/webauthn.js#L78
[decode]: https://github.com/Yubico/java-webauthn-server/blob/master/webauthn-server-demo/src/main/webapp/js/webauthn.js#L61
[fr]: https://developers.yubico.com/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/RelyingParty.html#finishRegistration-com.yubico.webauthn.FinishRegistrationOptions-

**Comment by hamfernandes** [comment]
After reviewing all, and thanks to your help I was able to overcome this error.
One more time, thank you very much @emlun.
