### ISSUE TITLE
U2F UserHandle validation failure when a single user has multiple devices registered

### ISSUE THREAD

**Issue by rksk** [Yubico/java-webauthn-server#313]
During the device registration, userHandle is populated with the userEntity.id as mentioned [here](https://www.w3.org/TR/webauthn/#dom-publickeycredentialuserentity-id). But it is possible to get userHandle as null during the authentication for FIDO U2F devices as mentioned [here](https://www.w3.org/TR/webauthn/#usecase-new-device-registration:~:text=2.2.1.%20Backwards,always%20be%20null.).

In the current implementation, it tires to get the userHandle from credentialRepository via getUserHandleForUsername() if the userHandle was null, [ref](https://github.com/Yubico/java-webauthn-server/blob/6adf0f8cb69d02e4980836ccb263526effdf03d8/webauthn-server-core/src/main/java/com/yubico/webauthn/FinishAssertionSteps.java#L148). But when there are multiple devices registered under the same username, it the credentialRepository might return one of them. Now when credentialRepository.lookup() is invoked with credential id and userHandle from [here](https://github.com/Yubico/java-webauthn-server/blob/6adf0f8cb69d02e4980836ccb263526effdf03d8/webauthn-server-core/src/main/java/com/yubico/webauthn/FinishAssertionSteps.java#L156), it won't match with any entry in the credentialRepository due to incorrect userHandle.

W3 says following [here](https://www.w3.org/TR/webauthn/#usecase-new-device-registration:~:text=Identify%20the%20user%20being%20authenticated%20and%20verify,value%20is%20the%20owner%20of%20credentialSource.). 

> Identify the user being authenticated and verify that this user is the owner of the public key credential source credentialSource identified by credential.id:
> 
> - If the user was identified before the authentication ceremony was initiated, e.g., via a username or cookie, verify that the identified user is the owner of credentialSource. If response.userHandle is present, let userHandle be its value. Verify that userHandle also maps to the same user.
> 
> - If the user was not identified before the authentication ceremony was initiated, verify that response.userHandle is present, and that the user identified by this value is the owner of credentialSource.
> 

But as far as I read the code, it seems we are always trying to validate both credentialId and userHandle.

It would be really great if you could help understanding whether this flow can be handled in a different way or needs to be fixed in the library.

**Comment by emlun** [comment]
Hi! This sounds like you are giving each credential a unique user handle, even credentials that belong to the same user. Is that the case? The user handle should be unique per user but shared between all credentials for that user.

**Comment by rksk** [comment]
Thank you @emlun for the reply. 

I believe we can use the same UserHandle during the registration if credentialRepository.getUserHandleForUsername() returns a value for the given user.

**Comment by emlun** [comment]
Sorry, I don't understand what you mean by that. Could you elaborate?

**Comment by emlun** [comment]
Yes, that is how the WebAuthn API (not just this library) is intended to be used. And yes, setting different user handles for different credentials for the same user will cause issues like the one you're seeing.

**Comment by emlun** [comment]
Happy to help, I'm glad it worked out!
