### ISSUE TITLE
Safari: Resident Key discouraged gives empty userHandle instead of null

### ISSUE THREAD

**Issue by fcorneli** [Yubico/java-webauthn-server#327]
I notices something weird when playing with YubiKeys.
When registering with option resident key discouraged, and next authenticating via Safari, the authentication response contains:
```
...
"userHandle":""
...
```
This makes the server side of course explode with:
```
com.yubico.webauthn.exception.AssertionFailedException: java.lang.IllegalArgumentException: User handle ByteArray() does not own credential ByteArray(...)
```
This while Google Chrome and Firefox give as authentication response the following:
```
...
"userHandle":null
...
```

**Comment by emlun** [comment]
This is a known bug in Safari: https://bugs.webkit.org/show_bug.cgi?id=239737

See also: #194

**Comment by fcorneli** [comment]
@emlun Thanks for the reference. Will `java-webauthn-server` implement a work-around for this, or should I "fix" the response myself?

**Comment by emlun** [comment]
No, `java-webauthn-server` will not implement a work-around for this.

In general it will depend on impact and what makes pragmatic sense, but in principle we do not intend to implement work-arounds for violations of the spec.
