### ISSUE TITLE
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot construct instance of `com.yubico.webauthn.data.Extensions$CredentialProperties$CredentialPropertiesOutput

### ISSUE THREAD

**Issue by alokkulkarni** [Yubico/java-webauthn-server#333]
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot construct instance of `com.yubico.webauthn.data.Extensions$CredentialProperties$CredentialPropertiesOutput

using webauthn java 2.6.0 alpha version

CredentialPropertiesOutput class is marked with @Builder but still faces a parsing issue and need to add a default constructor like the ones added form CredProps class.

if passing Extensions fails on this class as Jackson is not able to parse the @JsonCreator annotation and needs a default constructor to be added to the class.

pasted above the error when parsing the val credential : PublicKeyCredential<AuthenticatorAttestationResponse, ClientRegistrationExtensionOutputs> using springboot 3 jackson.

framework - springboot 3.1.5
Java version - 17
Kotlin version - 1.9.0

**Comment by emlun** [comment]
Can you share the JSON value you're attempting to parse?

**Comment by alokkulkarni** [comment]
"extensions": {
            "appidExclude": null,
            "credProps": true,
            "largeBlob": null,
            "uvm": null
        }

**Comment by emlun** [comment]
That's an extension input, not an extension output. Could you share the JSON of the `PublicKeyCredential` response, including extensions, that you are trying to parse?
