### ISSUE TITLE
May I ask if this software is controlled, led, or unrelated to the United States

### ISSUE THREAD

**Issue by trainKing-star** [Yubico/java-webauthn-server#356]
May I ask if this software is controlled, led, or unrelated to the United States

**Comment by emlun** [comment]
Hi! I forwarded this question to our legal team, this is their response:

YubiKeys are categorized under a NLR exception for US export control, however, Yubico cannot provide legal guidance with respect to export compliance and we recommend that you seek your own counsel.

You're welcome to re-open the issue if you have further questions, but please note that I may need to forward them to the legal team too.
