### ISSUE TITLE
404 attestation migration guide link on DYC

### ISSUE THREAD

**Issue by elukewalker** [Yubico/java-webauthn-server#368]
Steps to repo:
1. Click the webauthn-server-attestation "its own migration guide" on link on https://developers.yubico.com/java-webauthn-server/Migrating_from_v1.html (https://github.com/Yubico/java-webauthn-server/blob/362f1b401186a7e9e18011b5dc0c6fbf9786e8ad/doc/Migrating_from_v1.adoc?plain=1#L14)

Expectation:
2. webauthn-server-attestation migration page is displayed

Actual:
2. 404

Actions taken:
* I've updated the project's conf.json dyc to copy over the webauthn-server-attestation "Migrating_from_v1.adoc" to the DYC. See https://github.com/Yubico/developers.yubico.com/commit/1ed880049652586e4c15681f826569ad7133a951

Open question:
* The java-webauthn-server migration adoc uses the relative path "link:../webauthn-server-attestation" which works in the github project because it is the "doc" directory.  However, the java-webauthn-server migration guide is not in a "doc" folder when deployed to the DYC. The system builds the link "https://developers.yubico.com/webauthn-server-attestation/doc/Migrating_from_v1.html", which is missing the "java-webauthn-server" from the path. How should we resolve this?

**Comment by emlun** [comment]
Good catch, thanks!

I guess we could just hard-link to the developers page, even if you're reading the migration guide on GitHub?

**Comment by emlun** [comment]
This is now fixed as far as I can tell. Thanks!
