### ISSUE TITLE
Package com.yubico:webauthn-server-core:2.5.0 import failed

### ISSUE THREAD

**Issue by cosekw** [Yubico/java-webauthn-server#370]
We failed import package `com.yubico:webauthn-server-core:2.5.0`, because of missing the dependency `cbor-4.5.4`, is there any problem with the following repository?
![企业微信截图_17223987357648](https://github.com/user-attachments/assets/3844f3b4-6c4a-460a-b147-179555c7b601)

 By the way, we got `500` response when we try to access [cbor-4.5.4](https://repository.cloudera.com/repository/cloudera-repos/com/upokecenter/cbor/4.5.4/cbor-4.5.4.pom)
![image](https://github.com/user-attachments/assets/1de97d4c-85ca-4f1e-8b57-fbeb12856af7)

**Comment by emlun** [comment]
Yes, that would be a problem with the Cloudera repository. I would say to make sure the repository contains the `com.upokecenter:cbor` module, but the 500 response suggests that the service may be broken in some other way than simply not finding it. I'm afraid we can't help you much with this.

**Comment by cosekw** [comment]
Ok, thanks, we mistakely thought the dependency repository is specified by your side
