### ISSUE TITLE
webauthn-server-attestation: "friendlyNames" in MetadataStatement

### ISSUE THREAD

**Issue by jensle1** [Yubico/java-webauthn-server#377]
When using the FidoMetadataDownloader to download the MDS blob, i get an error: 
`Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "friendlyNames" (class com.yubico.fido.metadata.MetadataStatement$MetadataStatementBuilder), not marked as ignorable (27 known properties: "tcDisplayContentType", "tcDisplayPNGCharacteristics", "alternativeDescriptions", "attestationTypes", "attachmentHint", "publicKeyAlgAndEncodings", "isKeyRestricted", "attestationCertificateKeyIdentifiers", "tcDisplay", "keyProtection", "protocolFamily", "schema", "cryptoStrength", "authenticatorVersion", "legalHeader", "aaguid", "matcherProtection", "attestationRootCertificates", "authenticatorGetInfo", "icon", "aaid", "description", "isFreshUserVerificationRequired", "userVerificationDetails", "supportedExtensions", "upv", "authenticationAlgorithms"])` 

Looking at the blob file from https://mds.fidoalliance.org/, i can see, that there is a new field "friendlyNames", which is not metnioned in the specifications according to https://fidoalliance.org/specs/mds/fido-metadata-statement-v3.0-ps-20210518.html.

Should this field be added to the implementation?

**Comment by emlun** [comment]
Yes, this is a duplicate of #375, but thanks anyway for reporting. The new field is not yet added to the data model, but `FidoMetadataDownloader` will no longer throw errors when encountering unknown attributes.
