### ISSUE TITLE
WebAuthN server demo: display-name for registration is not optional

### ISSUE THREAD

**Issue by mmoayyed** [Yubico/java-webauthn-server#55]
I am trying out the webauthn-server-demo from the latest tip of the master branch as of today, (no local changes made; simply ran `gradlew run`) and I'm trying to test out the registration flow using the "Resident Credential" option with a YubiKey 5. 

Here is what I see:

1. Provide a username in the UI
2. Click "Register new account with resident credential"
3. Browser prompts to set up a PIN
4. I provide a PIN and confirmation PIN and click next.
5. See the error "DOMException: The operation either timed out or was not allowed. See: https://w3c.github.io/webauthn/#sec-assertion-privacy." in the console.

(The link also appears to point to a non-existing anchor tag and/or section)

At this point and once the pin is set up, I always see the error message above when I attempt register using that option. Tried the same scenario with Chrome, Firefox and Brave, all of which lead to the same error. The same error also pops up after resetting/removing the pin. The "Resident Credential" option does seem to work fine on webauthn.io

I suspect I might be missing something pretty obvious. How best can I troubleshoot this? 

PS The registration/authentication flow without a resident credential option works fine, on Chrome, Firefox and Brave.

**Comment by mmoayyed** [comment]
I should also point out that similar to https://github.com/Yubico/java-webauthn-server/issues/12 (which is about authentication), registration simply does not work on Chromium 79.0.3945.130. The browser does present the webauthn dialog asking for a security device, yet it never accepts it. 

To make sure, I tried this scenario on webauthn.io and Chrome does appear to work OK there. The same scenario also works on Firefox. I did compare the request between Chrome and Firefox, and they both seem identical. Not sure what else I could troubleshoot.

**Comment by emlun** [comment]
The demo works fine for me with a Security Key NFC by Yubico, in Chromium 79.0.3945.130 on Linux, but not in Firefox 72.0.2. What operating system are you using, and what authenticator?

**Comment by mmoayyed** [comment]
Thanks for the response!

I am on MacOS Mojave 10.14.6, Chrome 79.0.3945.130, Firefox Dev 73.0b12. Also tried with Brave which uses Chromium 79.0.3945.130 to same results. Using a Yubikey 5 NFC, as advertised here https://www.yubico.com/product/yubikey-5-nfc

I'll run some additional tests against Safari and maybe a more vanilla version of Chrome/Chromium with all plugins disabled. Are there any particular logs I should turn on to dig deeper?

**Comment by emlun** [comment]
Oh, I think I found what's going wrong. It fails if I don't enter anything into the display name field, but succeeds if I do. Does that match your results?

**Comment by mmoayyed** [comment]
Indeed! I have yet to verify this but that does match my earlier testing. I don't recall putting in a display name or a nickname for that matter. I'll confirm shortly with an actual test but you are right on point.

**Comment by mmoayyed** [comment]
Tested this again and indeed; the display name field is not treated as optional. If I put in a value, then registration passes OK.

**Comment by mmoayyed** [comment]
Forgot to mention that I can certainly put in a pull request, (or at least try!), if you deem this to require a fix. Otherwise we could close and call it my error :)

**Comment by emlun** [comment]
Thanks! But no need, it was a ~10 minute fix. :)

**Comment by mmoayyed** [comment]
Outstanding; I appreciate your time.
