### ISSUE TITLE
Invalid attestation signature

### ISSUE THREAD

**Issue by Silvercast** [Yubico/java-webauthn-server#6]
Hi,

I'm working on integrating WebAuthn to our system and I've hit an issue with incorrect "Invalid attestation signature" step 14 of [1] . Debugging gives me a weird value of `clientDataJsonHash`

The raw value of clientDataJSON is 
`eyJjaGFsbGVuZ2UiOiJYdDhuajNqQkJid1gtaWlsUGZpTEx5UFc4Z2NneEZZcU1xS0plME9mQTR3Iiwib3JpZ2luIjoibG9jYWxob3N0IiwidHlwZSI6IndlYmF1dGhuLmNyZWF0ZSJ9`

but the hash result is `WL6RneVupE03jwO5j8AZiGlj_scPVJ-b34C0b9pOVks`

which leads to invalid signature verification. I tried to compute a SHA-256 of the raw value [2], then base64 encode, and I saw a different value.

[1] https://github.com/Yubico/java-webauthn-server/blob/0382594b780122f5ff470ec71504218d6c8f1a0a/webauthn-server-core/src/main/java/com/yubico/webauthn/FinishRegistrationSteps.java#L427
[2] https://emn178.github.io/online-tools/sha256.html

Can you please explain that to me? Thanks

**Comment by emlun** [comment]
Hi,

How did you compute the hash when you saw a different value? I get the same when I try:

    $ echo -n eyJjaGFsbGVuZ2UiOiJYdDhuajNqQkJid1gtaWlsUGZpTEx5UFc4Z2NneEZZcU1xS0plME9mQTR3Iiwib3JpZ2luIjoibG9jYWxob3N0IiwidHlwZSI6IndlYmF1dGhuLmNyZWF0ZSJ9 | base64 -d | sha256sum
    58be919de56ea44d378f03b98fc019886963fec70f549f9bdf80b46fda4e564b  -

    $ echo -n WL6RneVupE03jwO5j8AZiGlj_scPVJ-b34C0b9pOVks= | tr _- /+ | base64 -d | xxd
    00000000: 58be 919d e56e a44d 378f 03b9 8fc0 1988  X....n.M7.......
    00000010: 6963 fec7 0f54 9f9b df80 b46f da4e 564b  ic...T.....o.NVK

**Comment by Silvercast** [comment]
not sure if it's my mistake. Look like the clientDataJSON doesn't have to be base64url encoded before going to hash function. FIDO2 standard says the clientDataJSON needs to be base64 encoded first, strange.

**Comment by emlun** [comment]
No worries. Where in the standard does it say that?

**Comment by Silvercast** [comment]
https://medium.com/@herrjemand/verifying-fido2-responses-4691288c8770 `response.clientDataJSON — base64url encoded buffer of the JSON structure that contains session information. That’s the only response field I will describe for now.
`

https://www.w3.org/TR/webauthn/ `Let clientDataJSON be the JSON-serialized client data constructed from collectedClientData.`

**Comment by emlun** [comment]
Oh, ok. The response object in Yuriy's article is an application-level representation of the PublicKeyCredential object returned from the WebAuthn API. The `clientDataJSON` returned from the API is a [raw `ArrayBuffer` value that is not base64 encoded][1].

The demo server in this repo also does the same translation as in Yuriy's article in order to transport the response from the client to the server, but then base64 decodes the values before working with them.

[1]: https://www.w3.org/TR/webauthn/#dom-authenticatorresponse-clientdatajson
