### ISSUE TITLE
Missing dependencies in Maven POM v1.6.1 

### ISSUE THREAD

**Issue by brbug** [Yubico/java-webauthn-server#62]
Hi,
Dependencies definitions are missing in the java-webauthn-server Maven POM since v1.6.1.
The previous version (1.6.0) pom was correctly defining this project's dependencies.

Evidences : compare the left block of the following pages :
* v1.6.1 : https://search.maven.org/artifact/com.yubico/webauthn-server-core/1.6.1/jar
* v1.6.0 : https://search.maven.org/artifact/com.yubico/webauthn-server-core/1.6.0/jar

The same problem seems to affect yubico-util projet.

Could you correct the project's pom ASAP ?
Thanks

**Comment by emlun** [comment]
Sorry, will fix this ASAP.

**Comment by emlun** [comment]
I have the changes ready to go, but I'm having some issues publishing the artifacts to the repositories. Hopefully it'll clear up soon.

**Comment by fkoepke** [comment]
I have this in my pom.xml:
```
<dependency>
	<groupId>com.yubico</groupId>
	<artifactId>yubico-util</artifactId>
	<version>1.6.1</version>
</dependency>

<dependency>
	<groupId>com.yubico</groupId>
	<artifactId>webauthn-server-core</artifactId>
	<version>1.6.1</version>
	<scope>compile</scope>
</dependency>
```

**Comment by emlun** [comment]
Release 1.6.2 is now out with the fix. Thanks for the report!

**Comment by codingchili** [comment]
Thanks for the 1.6.2 release,

Please update the dependency version in the README as I ran into this issue today.

**Comment by emlun** [comment]
Oops, sorry about that. I've updated the README and added that as a step in the release procedure.
