### ISSUE TITLE
[QUESTION]https://demo.yubico.com/webauthn-technical/registration prompt "Not implemented"

### ISSUE THREAD

**Issue by renyson** [Yubico/java-webauthn-server#83]
hi, I test yubico key on an android device.

1. download Chrome 83 on android device
2. open Chrome and load https://demo.yubico.com/webauthn-technical/registration
3. tap "NEXT" button
4. prompt "Not implemented"
![Screenshot_20200715-170117](https://user-images.githubusercontent.com/17057077/87531400-40b95980-c6c4-11ea-9c81-a1d6850647c3.png)

May I ask that is it a browser issue or android device issue? is there any way to print error log?
thanks~

**Comment by emlun** [comment]
The demo site runs a different implementation; I'll forward this internally to the people working on that.

**Comment by renyson** [comment]
Thanks! if there is a reply, could you please help to comment here, I want to find out whether it is related to the our android device.

**Comment by emlun** [comment]
Sorry, we can't quite tell what went wrong here. My hunch is that this might be some unimplemented attestation statement format.

If you see the same issue again, it would be helpful if you can tell us the time of the test, what timezone you're in and your Android and Chrome versions. Also if something comes up in the developer console. I'll close the issue for now.
