### ISSUE TITLE
InMemoryRegistrationStorage: querying by user-handle uses user-identity instead

### ISSUE THREAD

**Issue by mmoayyed** [Yubico/java-webauthn-server#87]
The `InMemoryRegistrationStorage` component has a method to look up registrations by user handles:

```java
    @Override
    public Collection<CredentialRegistration> getRegistrationsByUserHandle(ByteArray userHandle) {
        return storage.asMap().values().stream()
            .flatMap(Collection::stream)
            .filter(credentialRegistration ->
                userHandle.equals(credentialRegistration.getUserIdentity().getId())
            )
            .collect(Collectors.toList());
    }
```

What's strange here is that even though the method does imply a lookup by user-handles, leading one to suppose the query would be based on `credentialRegistration.getCredential().getUserHandle()`, the lookup is in fact based on `credentialRegistration.getUserIdentity().getId()` as the method shows.

Is this a bug where comparisons should be instead based on `credentialRegistration.getUserIdentity().getId()` or should the method name be changed to reflect something like `getRegistrationsByUserIdentity`, or am I completely off?

**Comment by emlun** [comment]
The user handle of a credential is the same thing as the ID of the associated user. The spec defines the `navigator.credentials.create()` option [`publicKey.user.id`](https://www.w3.org/TR/2020/WD-webauthn-2-20200730/#dom-publickeycredentialuserentity-id) as:

>The _user handle_ of the user account entity. A user handle is an opaque byte sequence with a maximum size of 64 bytes, and is not meant to be displayed to the user.

You're right that `credentialRegistration.getCredential().getUserHandle()` would also be correct - it holds the same value. If you look into `WebAuthnServer.java`, you'll find that whenever a `CredentialRegistration` instance is created, its `credential: RegisteredCredential` member always has its `userHandle` member set to the same value as the parent's `userIdentity` member.

Note, though, that the `WebAuthnServer`, `CredentialRegistration` and `InMemoryRegistrationStorage` classes are specific to the demo application - other applications using the library may use a different approach to setting the value of `RegisteredCredential.userHandle`. The `getRegistrationsByUserHandle` method is also specific to the demo.

**Comment by mmoayyed** [comment]
Thank you, Emil. Much appreciated.
