### ISSUE TITLE
Use of EC Keys produces - Point does not match field size

### ISSUE THREAD

**Issue by rajairside** [Yubico/java-webauthn-server#91]
I am using EC keys to register and I am getting the following error intermittently 
This is not happening every time 

```
Failed to parse public key from attestation data
at com.yubico.internal.util.ExceptionUtil.wrapAndLog(ExceptionUtil.java:34)
	at com.yubico.webauthn.PackedAttestationStatementVerifier.verifySelfAttestationSignature(PackedAttestationStatementVerifier.java:105)
	at com.yubico.webauthn.PackedAttestationStatementVerifier.verifyAttestationSignature(PackedAttestationStatementVerifier.java:90)
	at com.yubico.webauthn.FinishRegistrationSteps$Step14.lambda$validate$0(FinishRegistrationSteps.java:436)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.yubico.webauthn.FinishRegistrationSteps$Step14.validate(FinishRegistrationSteps.java:434)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.next(FinishRegistrationSteps.java:115)

....


Caused by: COSE.CoseException: Internal error on SPKI
	at COSE.OneKey.CheckECKey(OneKey.java:412)
	at COSE.OneKey.CheckKeyState(OneKey.java:307)
	at COSE.OneKey.<init>(OneKey.java:59)
	at com.yubico.webauthn.WebAuthnCodecs.importCoseP256PublicKey(WebAuthnCodecs.java:93)
	at com.yubico.webauthn.WebAuthnCodecs.importCosePublicKey(WebAuthnCodecs.java:77)
	at com.yubico.webauthn.PackedAttestationStatementVerifier.verifySelfAttestationSignature(PackedAttestationStatementVerifier.java:101)
	... 86 more
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: Invalid EC key
	at jdk.crypto.ec/sun.security.ec.ECKeyFactory.engineGeneratePublic(ECKeyFactory.java:157)
	at java.base/java.security.KeyFactory.generatePublic(KeyFactory.java:352)
	at COSE.OneKey.CheckECKey(OneKey.java:406)
	... 91 more
Caused by: java.security.InvalidKeyException: Invalid EC key
	at jdk.crypto.ec/sun.security.ec.ECPublicKeyImpl.parseKeyBits(ECPublicKeyImpl.java:111)
	at java.base/sun.security.x509.X509Key.decode(X509Key.java:390)
	at java.base/sun.security.x509.X509Key.decode(X509Key.java:401)
	at jdk.crypto.ec/sun.security.ec.ECPublicKeyImpl.<init>(ECPublicKeyImpl.java:71)
	at jdk.crypto.ec/sun.security.ec.ECKeyFactory.implGeneratePublic(ECKeyFactory.java:219)
	at jdk.crypto.ec/sun.security.ec.ECKeyFactory.engineGeneratePublic(ECKeyFactory.java:153)
	... 93 more
Caused by: java.io.IOException: Point does not match field size
	at java.base/sun.security.util.ECUtil.decodePoint(ECUtil.java:48)
	at jdk.crypto.ec/sun.security.ec.ECPublicKeyImpl.parseKeyBits(ECPublicKeyImpl.java:109)
	... 98 more


```

**Comment by emlun** [comment]
Thanks for the report! Could you post a few example authenticator responses that do trigger this error, and a few that don't? If you could provide the JSON for the `AuthenticatorAttestationResponse` objects, that would be great.

**Comment by emlun** [comment]
@rajairside Could you provide some more information as described above?

**Comment by rajairside** [comment]
Example of failed Registration Request

EC Key

> {
   "kty":"EC",
   "d":"AeJwFcOE7hDWgaFtZaA9FWV-8wAGfuqDhdQJc1ON6zXVb-7dInnSaXD-fCAL6qsaG44sLRgvweWbmzKZpb3jqsol",
   "use":"sig",
   "crv":"P-521",
   "kid":"6478dbb4-02e4-443d-bf1d-e92054cdf5be",
   "x":"AAE0GKb_4yhY-Nl-j1Mnw33t0Fo5TDvbbegDMYpB__zG2sbnuIvQEOEePeLlCVirr8cGfw6iTpwGqbf3OOt2FePf",
   "y":"Aemx4YoFMvPgWJAgBZHAKy3MhFKavPHir2YT7hRehru-HIOuuizVBEgwzVVC0ICCq-Rr-1lz8IUUhEVToI_6Jm7x"
}

Registration Request

> {
  "username" : "c280f136-9a20-4403-b82a-f90435b41167",
  "sessionToken" : "3PofMJ8641CKxsOSv7cgtUM09ATo_RFDJShm9py-SPM",
  "publicKeyCredentialCreationOptions" : {
    "rp" : {
      "name" : "https://rajhost:9090",
      "id" : "rajhost",
      "icon" : "https://rajhost:9090"
    },
    "user" : {
      "name" : "c280f136-9a20-4403-b82a-f90435b41167",
      "displayName" : "c280f136-9a20-4403-b82a-f90435b41167",
      "id" : "V0X0f-d6eA69Gj7Xk6KUb5iqrGREMv8sckgbv0nOhOc"
    },
    "challenge" : "9gezFcmGvJuWvAoaxaBXCE-ObQF5AXRp-JyE0_y8CiE",
    "pubKeyCredParams" : [ {
      "alg" : -7,
      "type" : "public-key"
    }, {
      "alg" : -8,
      "type" : "public-key"
    }, {
      "alg" : -257,
      "type" : "public-key"
    } ],
    "excludeCredentials" : [ ],
    "authenticatorSelection" : {
      "requireResidentKey" : true,
      "userVerification" : "preferred"
    },
    "attestation" : "direct",
    "extensions" : { }
  }
}

{
   "credential":{
      "id":"9u0jkxlMNgDNDgFgoiwjBMjIpcs8MLV657zocx1pxjk",
      "response":{
         "attestationObject":"v2dhdHRTdG10v2NzaWdYijCBhwJBY_5RcZSkEziTjM7Tb3uvizo2pK8a4e_3gRpI6DEoDApl52o3Hk7LaOHeP7Nnt_fmaQueq-VkUfvDSiOM8jblIcsCQgHu3qkzKT_zDOwyrJbZdGvVUqo2E3BE8YwzF90--xMN_vlQE6A9foKMM29YY65E6TOmzgjjwTrMqb61AXZN5a_l32NhbGcm_2hhdXRoRGF0YVjnD9J-MkQVNOLuBESb1rkUPsHF7Yn3frh6FLiimYoFIRtFAAAFOQABAgMEBQYHCAkKCwwNDg8AIPbtI5MZTDYAzQ4BYKIsIwTIyKXLPDC1eue86HMdacY5pQMmAQIgAyFYQQE0GKb_4yhY-Nl-j1Mnw33t0Fo5TDvbbegDMYpB__zG2sbnuIvQEOEePeLlCVirr8cGfw6iTpwGqbf3OOt2FePfIlhCAemx4YoFMvPgWJAgBZHAKy3MhFKavPHir2YT7hRehru-HIOuuizVBEgwzVVC0ICCq-Rr-1lz8IUUhEVToI_6Jm7xY2ZtdGZwYWNrZWT_",
         "clientDataJSON":"eyJvcmlnaW4iOiJodHRwczovL3Jhamhvc3Q6OTA5MCIsImNoYWxsZW5nZSI6IjlnZXpGY21Hdkp1V3ZBb2F4YUJYQ0UtT2JRRjVBWFJwLUp5RTBfeThDaUUiLCJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2xpZW50RXh0ZW5zaW9ucyI6e319"
      },
      "clientExtensionResults":{
         
      },
      "type":"public-key"
   },
   "sessionToken":"3PofMJ8641CKxsOSv7cgtUM09ATo_RFDJShm9py-SPM"
}

**Comment by rajairside** [comment]
Example of successful request

> {
  "username" : "e8a51e4a-52e6-4428-85de-5e9e75e36463",
  "sessionToken" : "TpiYyGrEIhe5xEa5MhLshJtHWSIKcrmj0iQIbFKLLTQ",
  "publicKeyCredentialCreationOptions" : {
    "rp" : {
      "name" : "https://rajhost:9090",
      "id" : "rajhost",
      "icon" : "https://rajhost:9090"
    },
    "user" : {
      "name" : "e8a51e4a-52e6-4428-85de-5e9e75e36463",
      "displayName" : "e8a51e4a-52e6-4428-85de-5e9e75e36463",
      "id" : "G4J2bnVEy8w6emI9YA3pngH1hhCPjUqbGyjLI-MDL-o"
    },
    "challenge" : "bpdD3lZ8xmSudlLhRxnVledvzLi0-gaIcSMTB-JtevE",
    "pubKeyCredParams" : [ {
      "alg" : -7,
      "type" : "public-key"
    }, {
      "alg" : -8,
      "type" : "public-key"
    }, {
      "alg" : -257,
      "type" : "public-key"
    } ],
    "excludeCredentials" : [ ],
    "authenticatorSelection" : {
      "requireResidentKey" : true,
      "userVerification" : "preferred"
    },
    "attestation" : "direct",
    "extensions" : { }
  }
}
EC KEY Pair{"kty":"EC","d":"AF3a_zSHtrRaJeNlCzRsbdjHwiwx8IYApKOEyvflCHnkAHp6xOrg0pQmBBXyfUReRaEVXgQNhN7PMX9KsjVZcjji","use":"sig","crv":"P-521","kid":"e7fd81b8-b9df-418d-a3f2-ea96ab6eb2b9","x":"AfTlX16F9tSCSNTkA8I2AbGbQtzye5SsAEt3pDkbBsM1juc1GE1E2qVCu835U6aa-DwILhXPWqj9Cu2H_iSPMjnD","y":"AYR3CgP5ugvVhsXMn3G6LEVzemklQT8bQgVHuK5JESGIRNHL2wwuhh8IzbKKHCHs9SOq98cLr3xEOPk-OqJOeZMh"}
{
  "credential" : {
    "id" : "bhYNz5g8fyoyIxAccfZ9sl_Agl9z5wBtSHaNmGX-BLA",
    "response" : {
      "attestationObject" : "v2dhdHRTdG10v2NzaWdYizCBiAJCAP4zkSNsknUtVUVWB0Pfst-b2lWof1Q1eorWi__O-YW0TsVncAuye91oBXy6nJW99_nHs0bmyaUWvT_sns_HFgduAkIA2WJcAh5QwkgzveGahVcCkEAo8Kp5UAtCQNXmlkKmeaB-F4-ubX14pvniXkjStOLrYlXlCNQMUPuckQameh2Kb31jYWxnJv9oYXV0aERhdGFY6A_SfjJEFTTi7gREm9a5FD7Bxe2J9364ehS4opmKBSEbRQAABTkAAQIDBAUGBwgJCgsMDQ4PACBuFg3PmDx_KjIjEBxx9n2yX8CCX3PnAG1Ido2YZf4EsKUDJgECIAMhWEIB9OVfXoX21IJI1OQDwjYBsZtC3PJ7lKwAS3ekORsGwzWO5zUYTUTapUK7zflTppr4PAguFc9aqP0K7Yf-JI8yOcMiWEIBhHcKA_m6C9WGxcyfcbosRXN6aSVBPxtCBUe4rkkRIYhE0cvbDC6GHwjNsoocIez1I6r3xwuvfEQ4-T46ok55kyFjZm10ZnBhY2tlZP8",
      "clientDataJSON" : "eyJvcmlnaW4iOiJodHRwczovL3Jhamhvc3Q6OTA5MCIsImNoYWxsZW5nZSI6ImJwZEQzbFo4eG1TdWRsTGhSeG5WbGVkdnpMaTAtZ2FJY1NNVEItSnRldkUiLCJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2xpZW50RXh0ZW5zaW9ucyI6e319"
    },
    "clientExtensionResults" : { },
    "type" : "public-key"
  },
  "sessionToken" : "TpiYyGrEIhe5xEa5MhLshJtHWSIKcrmj0iQIbFKLLTQ"
}

**Comment by rajairside** [comment]
Please note this is happening when we trigger out tests from our mac/linux hosts.   We have IOS app as the client and we have so far not seen this issue at all from the last 6 months.  Our Android App uses RSA keys and use of RSA keys on all platforms is perfectly working.  

Our guess is that it could be with EC Key generation or CBOR serialization of the EC key - as mentioned in the above stack trace.

**Comment by emlun** [comment]
Ok, I'll look into that. Thanks! Is this happening every time on iOS, or only sometimes?

**Comment by rajairside** [comment]
We have not seen happening in IOS - just only mac or linux variants - Thanks

**Comment by emlun** [comment]
Sorry for leaving this for so long. Are you still having these issues?

Anyway, I finally took a closer look. It looks like the issue is that the Java KeyFactory requires the coordinates of P-521 keys to be exactly 66 bytes long, and the failing key you shared has an X coordinate only 65 bytes long. Looks like this happens when the first byte is all zeroes. So if it's your own code generating these keys, you can probably fix it by zero-padding the X/Y coordinates to 66 bytes long before serializing them to CBOR.

Please note, though, that the WebAuthn spec has now clarified that the COSEAlgorithmIdentifier `ES256` (-7) must only be used with the P-256 curve, so for P-521 you'd have to use `ES512` (-36). See: https://w3c.github.io/webauthn/#sctn-alg-identifier . Incidentally it still works with this library right now (well, when the byte arrays aren't too short), because the COSE format contains enough information to unambiguously determine the curve and signature algorithm anyway, but that might change in the future.

**Comment by emlun** [comment]
Closing this as inactive, you're welcome to re-open it if you continue having issues with this. Apologies again for the slow response.
