### ISSUE TITLE
Support for new "apple" attestation format?

### ISSUE THREAD

**Issue by billylo1** [Yubico/java-webauthn-server#93]
Hi, we are looking to support Safari 14 on iOS and Mac...  any chance this can be added to the Java webauthn server soon?  (cross-referencing the [issue ](https://github.com/Yubico/python-fido2/issues/100)posted on the python server)

Thanks.

**Comment by emlun** [comment]
Hi, yes, we will definitely implement support for it, but I'm not sure when it can happen exactly. I think late January at worst, but hopefully within a couple of weeks from now.

**Comment by billylo1** [comment]
thanks for the update, @emlun.  If there is anything I can help, feel free to DM me.  Looking forward to the upgrade.  Safari+iOS+Touch ID is an important element (probably the final missing piece) for the ecosystem to take flight.

**Comment by yaitskov** [comment]
+1

**Comment by billylo1** [comment]
Hi, @emlun, any good news to share? Billy.

**Comment by emlun** [comment]
Sorry, I should have updated here sooner. My estimate back in December was based on a couple of incorrect assumptions, so it's looking more like March now, unfortunately.

**Comment by billylo1** [comment]
thanks for the update... would it be possible to make an early alpha build so we can work in parallel as you fine-tune the final product?

**Comment by billylo1** [comment]
> Sorry, I should have updated here sooner. My estimate back in December was based on a couple of incorrect assumptions, so it's looking more like March now, unfortunately.

Any luck? @emlun

**Comment by emlun** [comment]
@billylo1 Sorry, we've kept you waiting on this for too long already. It's now implemented in PR #118 and published as pre-release version 1.9.0-RC1, it should come up on Maven Central shortly. Please give that a try and see if that works for you! If that looks good we'll go ahead and make it a full release as soon as you give the green light, otherwise we'll let it sit for about two weeks and promote it to full release if no issues have come up by then.

**Comment by billylo1** [comment]
No problem... will grab the updates and report back here.

**Comment by karsonkoo1** [comment]
@emlun 
I work for @billylo1.   I was trying to update to 1.9.0-RC1 but I'm getting the following error:
- Could not find com.yubico:webauthn-server-parent:1.9.0-RC1

I looked at the maven pom file for webauthn-server-core, it has a dependency for webauthn-server-core-minimal:1.9.0-RC1.
Looking at the pom file for webauthn-server-core-minimal (https://search.maven.org/remotecontent?filepath=com/yubico/webauthn-server-core-minimal/1.9.0-RC1/webauthn-server-core-minimal-1.9.0-RC1.pom), it has a dependency for webauthn-parent-server:1.9.0-RC1 and this artifact doesn't exist.  

Please correct me if I'm wrong.

**Comment by emlun** [comment]
Ah, I see. I've traced this to commit 3a03f821fbedc3ca98133c83fa8067d7aea1bfee, looks like that introduces a new artifact that also needs to be published. I'll get that fixed ASAP, thanks for pointing it out!

**Comment by emlun** [comment]
Ok, `1.9.0-RC2` is out now and looks like it should be fixed. Please give it another try!

**Comment by karsonkoo1** [comment]
Thanks @emlunk RC2 works! Now let us test this out. :)

**Comment by karsonkoo1** [comment]
@emlun, what's the time line for a GA release for 1.9.0?  so far it's looking good for us.  Thanks.

**Comment by emlun** [comment]
Great, thanks! Currently it's scheduled for 2021-05-03, but we can make it sooner if you want. For example, Tuesday next week (2021-04-27)? I'll need to check that there are no blockers, but I'm pretty confident there are none.

**Comment by karsonkoo1** [comment]
@emlun, we're good with the currently schedule 21-05-03.  thanks!

**Comment by emlun** [comment]
This is now released in version 1.9.0. Thanks for your help, and sorry for keeping you waiting for so long!

**Comment by karsonkoo1** [comment]
@emlun, I have a question.  Although this 1.9.0 supports apple's attestation format, the RegistrationResult came back with Attestation not being trusted.  In addition, the Attestation Metadata are mostly empty when I try to register my iPhone 7's Touch ID:

`attestationMetadata=Optional[Attestation(trusted=false, metadataIdentifier=Optional.empty, vendorProperties=Optional.empty, deviceProperties=Optional.empty, transports=Option.empty)]`

Using my Yubikey has no issues and I'm getting all the metadata back with no issues.  Any idea?

Thanks

**Comment by emlun** [comment]
Yes, the `webauthn-server-attestation` module bundles attestation root certs and metadata for Yubico devices only. To verify the full signature chain for Apple attestations you'll need to add Apple's attestation cert to your `MetadataService` implementation's trust store.

You can find Apple's attestation certificates here: https://www.apple.com/certificateauthority/private/

the tests contain an example of how that attestation metadata could be expressed in Yubico's `metadata.json` format: https://github.com/Yubico/java-webauthn-server/blob/b92e4470ddf8082deb359343ea31718fc0ac0b48/webauthn-server-attestation/src/test/scala/com/yubico/webauthn/attestation/DeviceIdentificationSpec.scala#L304-L326

and the demo app provides an example of adding additional trust roots to the bundled `StandardMetadataService`: https://github.com/Yubico/java-webauthn-server/blob/b92e4470ddf8082deb359343ea31718fc0ac0b48/webauthn-server-demo/src/main/java/demo/webauthn/WebAuthnServer.java#L114-L124

Does that help?

**Comment by karsonkoo1** [comment]
@emlun, yes, this helps!  Just wondering, where could we get the json that has all the apple devices for the metadata?

**Comment by emlun** [comment]
I don't know of an official one. But the test linked above shows an example of how you could construct a Yubico-formatted `metadata.json` file with metadata for Apple devices.

There is the [FIDO Metadata Service](https://fidoalliance.org/metadata/) (MDS), but I haven't yet checked whether that includes any Apple devices.
