### ISSUE TITLE
415 error

### ISSUE THREAD

**Issue by travisspencer** [Yubico/java-webauthn-server#95]
I am trying to run the demo app. I've done `./gradlew run` as well as compiling the WAR and hosting that in the newest version of Jetty. Both produce a 415 error:

```http
HTTP/2.0 415 Unsupported Media Type
Server: Jetty(9.4.32.v20200930)
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
```

for this request:

```http
POST https://localhost:8555/api/v1/authenticate HTTP/2.0
content-length: 15
pragma: no-cache
cache-control: no-cache
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
content-type: application/x-www-form-urlencoded;charset=UTF-8
accept: */*
origin: https://localhost:8555
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty
referer: https://localhost:8555/
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
cookie: ssm=ssm
cookie: username=eyJ1biI6InRlZGRpZSJ9###98b3a02c2ff78fc9d1e48d2e6277a1b7175ae40e569cf89da9e1cd06481931a1
host: localhost:8555
```

It sounds very much like [this SO post](https://stackoverflow.com/questions/65144907/http-415-unsupported-media-type-in-jetty-server) where the Jackson data binding is causing the content type to be incorrectly set.

Is this only happening for me?

**Comment by travisspencer** [comment]
My guess is that this is due to a recent change in Jetty 9.4.32. This project is allowing `org.eclipse.jetty:jetty-servlet:[9.4.9.v20180320,10)`, so I think this might have gotten broken on Sept. 30, 2020 when that new version of Jetty came out. See eclipse/jetty.project#5285.

**Comment by travisspencer** [comment]
Maybe not. Same with Jetty 9.4.30 that came in June before that change was released.

```http
HTTP/2.0 415 Unsupported Media Type
Server: Jetty(9.4.30.v20200611)
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
```

**Comment by emlun** [comment]
Confirmed, and it is a broken dependency but a different one. Looks like `org.glassfish.jersey.containers:jersey-container-servlet` broke in version `2.33`; it works fine with `2.32` but not fails like you describe with `2.33`. Thanks for the report!
