### ISSUE TITLE
exception because registration reponse includes a rawId

### ISSUE THREAD

**Issue by travisspencer** [Yubico/java-webauthn-server#96]
I keep getting an error on the registration response. From the README, it would be this step:

```
String responseJson = /* ... */;
PublicKeyCredential<AuthenticatorAttestationResponse, ClientRegistrationExtensionOutputs> pkc =
    PublicKeyCredential.parseRegistrationResponseJson(responseJson);
```

This produces this exception:

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "rawId" (class 
com.yubico.webauthn.data.PublicKeyCredential), not marked as ignorable (4 known properties: 
"response", "clientExtensionResults", "id", "type"])
 at [Source: (String)"{
"type":"publickey",
"id":"3annUSJTnvwGG...",
"rawId":"3annUSJTnvwGG...",
"response":{"clientDataJSON":"eyJjaGFsbGVuZ...","attestationObject":"o2NmbXRkbm9uZ"[truncated 320 chars]; 
line: 1, column: 821] (through reference chain: com.yubico.webauthn.data.PublicKeyCredential["rawId"])
```

The JSON in `responseJson` looks like this:

```
{
  "type": "public-key",
  "id": "3annUSJTnvwGGUjVQQMuz9HMy4GSc6e1EvairulG1iiUp6NyPkfPBj7_qc10-yS37dPaALSzD4D0cP0yrbffdw",
  "rawId": "3annUSJTnvwGGUjVQQMuz9HMy4GSc6e1EvairulG1iiUp6NyPkfPBj7_qc10-yS37dPaALSzD4D0cP0yrbffdw",
  "response": {
    "clientDataJSON": "eyJjaGFsbGVuZ2UiOiJNdXVfYlFiZWJZM0RkZVIyRzNjTUllV01BMGtYTjU0TU5walNjUk5CYlVJIiwiY2xpZW50RXh0ZW5zaW9ucyI6e30sImhhc2hBbGdvcml0aG0iOiJTSEEtMjU2Iiwib3JpZ2luIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6ODQ0MyIsInR5cGUiOiJ3ZWJhdXRobi5jcmVhdGUifQ",
    "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVjESZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2NBAAAAAAAAAAAAAAAAAAAAAAAAAAAAQN2p51EiU578BhlI1UEDLs_RzMuBknOntRL2oq7pRtYolKejcj5HzwY-_6nNdPskt-3T2gC0sw-A9HD9Mq2333elAQIDJiABIVgg2sckb53TQEcV-jfkwUMv4sHYo68NjPw_rDiF-WcMtL0iWCB7cFSIjtK6ejh6D039t4jp_FLSn2-nQZx23jJQQzMsyQ"
  },
  "clientExtensionResults": {}
}
```

I see `rawId` is in there, but shouldn't it be? When I look at the [create API](https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/create) on MDN, [it says](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential#Properties) it returns `PublicKeyCredential` which has a `rawId`. I got this by calling `create` from the [GitHub WebAuthn JavaScript lib](https://github.com/github/webauthn-json#usage). Is that adding something it shouldn't?

**Comment by emlun** [comment]
Hi,

Yes, `id` and `rawId` are two representations of the same data. In this library we chose to allow only one of them, to avoid possible issues if they were to contain different data, and we chose `id` since it comes prepackaged as a JSON-friendly string value. Your issue should be easy to fix by simply omitting `rawId` from the payload you send into the java-webauthn-server library.

**Comment by travisspencer** [comment]
Yes, that's what I did, but it would be helpful if this lib accepted it and failed if `id` and `rawId` where both present and didn't match. That would be more inline with my expectations as a newbie coming to this lib, and make the client code a simple pass through to the server validation logic.

**Comment by emlun** [comment]
Noted, that seems like a reasonable improvement to make. Thanks for the suggestion!
