### ISSUE TITLE
Make dependency on Bouncy Castle optional or remove entirely

### ISSUE THREAD

**Issue by travisspencer** [Yubico/java-webauthn-server#97]
We would like to use core of this library without depending on Bouncy Castle. From what I can tell, many of its usages can be replaced with things in Java SE and other popular libraries (like Apache Commons Codec or Guava). Some things I've seen that it's being used for beyond the "basics" are EDDSA support, ANS1 parsing, and curve type verification. These can be done without Bouncy Castle though, so having this as a hard requirement seems unnecessary. Therefore, I'd like to propose that this dependency be made optional or entirely removed by:

1. Replacing usages of it with other APIs from Java SE or other current dependencies (e.g., Guava) or, perhaps, new dependencies if required (e.g., Apache Commons Codec)
2. Making the crypto provider pluggable, preferably using the existing system in Java for doing so.

If these things are done, then the dependency can be removed or marked as optional in the gradle build. In the latter case, consumers of this lib can choose if they want to depend on it or not.

**Comment by emlun** [comment]
Hi! This definitely seems worthwhile to do, but unfortunately I don't have the time to look into this right now. Sorry, I'll let you know when I do.

**Comment by emlun** [comment]
Fixed in #98. Thanks again!
